baseURL = "https://jmattheis.de/"
languageCode = "en-us"
title = "/dev/jmattheis"
theme = "modified-theme"
publishDir = "docs"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 20

enableRobotsTXT = false
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false
[permalinks]
  blog = "/blog/:year/:month/:title/"

[author]
  name = "Jannis Mattheis"

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Nice theme for homepages and blogs"
  keywords = ""
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "blog"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "/dev/jmattheis"
    logoHomeLink = "/"
    # Set to a valid CSS color to change the cursor in the logo.
    # logoColor    = "#67a2c9"

  [[params.social]]
    name = "email"
    url  = "mailto:contact@jmattheis.de"

  [[params.social]]
    name = "github"
    url  = "https://github.com/jmattheis"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/4244993/jmattheis"
